name: run tests

on:
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Dotnet CORE 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Restore
        run: dotnet restore .

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
        
